version: '3.4'

services:
  postgres:
    image: postgres:latest
    container_name: db-apidoemail
    environment:
      POSTGRES_DB: apidoemail
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    restart: always
    ports:
      - "5432:5432"